[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
rustyline = "10.0"
core = { path = "../core" }
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }